services:
  registry-ui:
    image: joxit/docker-registry-ui:main-debian
    environment:
      - DELETE_IMAGES=true
      - NGINX_PROXY_PASS_URL=http://registry-server:5000
      - SINGLE_REGISTRY=true
      - SHOW_CATALOG_NB_TAGS=true
      - SHOW_CONTENT_DIGEST=true
      - TAGLIST_PAGE_SIZE=100
      - REGISTRY_SECURED=false
      - REGISTRY_TITLE=Coder Docker Registry
    ports:
      - 8081:80
    container_name: registry-ui
  registry-server:
    container_name: registry-server
    image: registry:3
    volumes:
      - ./config.yml:/etc/distribution/config.yml
      - ./data:/var/lib/registry
